status = error
name = CDLauncherLog4j2

appender.consola.type = Console
appender.consola.name = STDOUT
appender.consola.target = SYSTEM_OUT
appender.consola.layout.type = PatternLayout

# FORMATO IDÉNTICO AL ProxyLog4j2
appender.consola.layout.pattern = [%d{HH:mm:ss}] [%t/%level]: %msg%n

rootLogger.level = all
rootLogger.appenderRefs = consola
rootLogger.appenderRef.consola.ref = STDOUT
