#Configuración de CrashDetectorMC
#Sun Jun 15 22:33:23 PDT 2025
color_error=FF6347
color_caja_texto=3C3C3C
color_de_titulos_de_consolas=56CCF2
api_de_registros_seleccionada=SecureLogger
color_titulo=56CCF2
color_enlace_texto=56CCF2
color_info=FFFFFF
color_enlace=56CCF2
anonimizar_registros=true
color_boton=46468C
sitio_de_registros_seleccionado=https\://securelogger.net/save/log?
sito_de_informes=https\://asbestosstar.egoism.jp/crash_detector/crash_detector_servidor.rb
color_fondo=282828
color_texto=FFFFFF
color_advertencia=FFD700
